# Generated by Django 4.0.6 on 2022-08-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='catalog/categories/static/images/categories'),
        ),
    ]
