# Generated by Django 4.0.6 on 2022-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_subcategory_subsubcategory_delete_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/static/images/categories'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/static/images/subcategories'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/static/images/subcategories'),
        ),
    ]
