# Generated by Django 4.0.6 on 2022-08-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_image_alter_subcategory_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsubcategory',
            old_name='category',
            new_name='subcategory',
        ),
    ]
