# Generated by Django 4.0.6 on 2022-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_category_subsubcategory_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ManyToManyField(to='catalog.subcategory'),
        ),
    ]
