# Generated by Django 4.0.6 on 2022-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Номер телефону', max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, upload_to='catalog/static/images/about')),
            ],
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
