# Generated by Django 4.0.6 on 2022-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_product_boiler_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='boiler_type',
            field=models.CharField(blank=True, choices=[('газ', 'Газовий'), ('рід', 'Рідкопаливний'), ('ком', 'Комбінований'), ('твр', 'Твердопаливний'), ('ел', 'Електричний')], max_length=3, verbose_name='Тип котла'),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_heater_type',
            field=models.CharField(blank=True, choices=[('нак', 'Накопичувальний'), ('прт', 'Проточний')], max_length=3, verbose_name='Тип водонагрівача'),
        ),
        migrations.AlterField(
            model_name='product',
            name='work_type_of_gas_boiler',
            field=models.CharField(blank=True, choices=[('стн', 'Стандартний'), ('кнд', 'Конденсаційний')], max_length=3, verbose_name='Принцип роботи газового котла'),
        ),
        migrations.AlterField(
            model_name='product',
            name='work_type_of_solid_fuel_boiler',
            field=models.CharField(blank=True, choices=[('дтг', 'Довготривалого горіння'), ('пел', 'Пелетний'), ('пір', 'Піролізний'), ('стн', 'Стандартний')], max_length=3, verbose_name='Принцип роботи твердопаливного котла'),
        ),
    ]
