# Generated by Django 4.0.6 on 2022-08-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_product_boiler_purpose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_and_date',
            new_name='discount_end_date',
        ),
    ]
