# Generated by Django 4.0.6 on 2022-09-01 20:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_rename_discount_and_date_product_discount_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=999999, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Вкажіть назву продукту', max_length=300, verbose_name='Назва'),
        ),
    ]
