# Generated by Django 4.0.6 on 2022-09-07 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(help_text='Наприклад: Євро - Гривня', max_length=200, verbose_name='Назва курсу')),
                ('currency_value', models.IntegerField(blank=True, null=True, verbose_name='Значення')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.currency'),
        ),
    ]
