# Generated by Django 4.0.6 on 2022-09-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Значення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='boiler_capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Місткість водонагрівача (л)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coefficient_of_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ККД (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Акційна ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='electric_power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Електрична потужність (кВт)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heat_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Максимальна площа обігріву (кв м)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heating_power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Теплова потужність (кВт)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Висота (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Глибина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_fuel_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Максимальна витрата палива (м3/год)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_temperature_water_heating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Максимальна температура нагріва води (°С)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pressure_in_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Тиск на вході (max атм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pressure_in_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Тиск на вході (min атм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productivity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Продуктивність (л/хв)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Вага (кг)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ширина (мм)'),
        ),
    ]
