# Generated by Django 4.0.6 on 2023-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_rename_description_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Марка та модель'),
        ),
        migrations.AddField(
            model_name='order',
            name='problem_description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Опис проблеми'),
        ),
    ]
