version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    command: >
      certbot renew
      && nginx -s reload
    depends_on:
      - nginx
  mysqldb:
    # image: 'mysql'
    build: ./mysql
    ports:
      - 3308:3306
    volumes: 
      # - vts-volume4:/var/lib/mysql
      - vts-volume-test:/docker-entrypoint-initdb.d
      # - ./vts_dump.sql:/docker-entrypoint-initdb.d/vts_dump.sql
    # env_file:
    #   - ./.env
    environment:
      - NOVA_POSHTA_API_KEY=60635140d18ae9c0354f3158bc6c77bb
      - SECRET_KEY=django-secure-q9b8he4opv6-p*@0vbNma05oh_+Liccdz_m5n0wzd1zj
      - DB_USERNAME=viacheslav
      - DB_PASSWORD=slavon360
      - MYSQL_USER=viacheslav
      - MYSQL_PASSWORD=slavon360
      - MYSQL_ROOT_PASSWORD=slavon360
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=vts_db
      - DJANGO_DEBUG=True
      - DEV_MODE=False
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 1s
      retries: 10
    # depends_on:
    #   - frontend
  # migration:
  #   build: 
  #     context: ./backend
  #     dockerfile: migration.dockerfile
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mysqldb
    # command: mysql -uroot root -p slavon360 -e "create database vts_db;"
  # mysqlinit:
  #   image: 'mysql'
  #   volumes:
  #     - vts-volume1:/var/lib/mysql
  #   command: bash -c "sleep 20 && mysql -h mysqldb -uviacheslav -pslavon360 vts_db < ./vts_dump.sql"
  #   # depends_on:
  #   #   - mysqldb
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - builded-frontend:/backend/catalog/static
  #   tty: true
    # depends_on:
    #   - mysqldb
          # condition: service_healthy
      # - backend
    # command: nodemon ./frontend/js scripts-bundler.js --env development --all
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    # command: bash -c "sleep 30" 
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      # - builded-frontend:/./app/catalog/static
    # env_file:
    #   - ./.env
    #   - ./production/.env
    environment:
      - NOVA_POSHTA_API_KEY=60635140d18ae9c0354f3158bc6c77bb
      - SECRET_KEY=django-secure-q9b8he4opv6-p*@0vbNma05oh_+Liccdz_m5n0wzd1zj
      - DB_USERNAME=viacheslav
      - DB_PASSWORD=slavon360
      - MYSQL_USER=viacheslav
      - MYSQL_PASSWORD=slavon360
      - MYSQL_ROOT_PASSWORD=slavon360
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=vts_db
      - DJANGO_DEBUG=True
      - DEV_MODE=False
      - RUN_FROM_DOCKER=True
    depends_on:
      mysqldb:
          condition: service_healthy
      # - migration
      # - mysqlinit
    tty: true
volumes:
  vts-volume-test:
  # builded-frontend:
