# Generated by Django 4.0.6 on 2022-08-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_subsubcategory_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Категорії',
        ),
    ]
