# Generated by Django 4.0.6 on 2022-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_phone_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, upload_to='about'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='subcategories'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='subcategories'),
        ),
    ]
