# Generated by Django 4.0.6 on 2022-08-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_product_boiler_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_temperature_water_heating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальна температура нагріва води (°С)'),
        ),
    ]
