# Generated by Django 4.0.6 on 2022-08-28 19:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(help_text='Опис'),
        ),
    ]
