# Generated by Django 4.0.6 on 2022-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_product_boiler_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='boiler_purpose',
            field=models.CharField(blank=True, choices=[('двоконтурний', 'Двоконтурний'), ('одноконтурний', 'Одноконтурний')], max_length=100, verbose_name='Призначення котла'),
        ),
        migrations.AlterField(
            model_name='product',
            name='boiler_type',
            field=models.CharField(blank=True, choices=[('газовий', 'Газовий'), ('рідкопаливний', 'Рідкопаливний'), ('комбінований', 'Комбінований'), ('твердопаливний', 'Твердопаливний'), ('електричний', 'Електричний')], max_length=100, verbose_name='Тип котла'),
        ),
        migrations.AlterField(
            model_name='product',
            name='combustion_chamber_type',
            field=models.CharField(blank=True, choices=[('відчинена', 'Відчинена'), ('зачинена', 'Зачинена')], max_length=100, verbose_name='Тип камери згорання'),
        ),
        migrations.AlterField(
            model_name='product',
            name='control_type',
            field=models.CharField(blank=True, choices=[('механічне', 'Механічне'), ('електронне', 'Електронне')], max_length=100, verbose_name='Тип керування'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('дизель', 'Дизель'), ('деревина', 'Деревина'), ('кокс', 'Кокс'), ('пелети', 'Пелети'), ('природній газ', 'Природній газ'), ('скраплений газ', 'Скраплений газ'), ('солома', 'Солома'), ('торфобрикети', 'Торфобрикети/Торф'), ('вугілля', 'Вугілля'), ('електрика', 'Електрика')], max_length=100, verbose_name='Вид палива'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heat_carrier_type',
            field=models.CharField(blank=True, choices=[('вода', 'Вода'), ('етиленгліколь', 'Етиленгліколь'), ('пропіленгліколь', 'Пропіленгліколь'), ('суміші', 'Суміші')], max_length=100, verbose_name='Вид теплоносія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heat_exchanger_material',
            field=models.CharField(blank=True, choices=[('сталь', 'Сталь'), ('нержавіюча сталь', 'Нержавіюча сталь'), ('чавун', 'Чавун'), ('мідь', 'Мідь')], max_length=100, verbose_name='Матеріал теплообмінника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heating_element',
            field=models.CharField(blank=True, choices=[('трубчастий', 'Трубчастий'), ('спіральний', 'Спіральний'), ('сухий', 'Сухий'), ('мокрий', 'Мокрий')], max_length=100, verbose_name='Нагріваючий елемент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('газовий', 'Газовий'), ('комбінований', 'Комбінований'), ('непрямий', 'Непрямий'), ('електричний', 'Електричний')], max_length=100, verbose_name='Тип опалення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ignition_type',
            field=models.CharField(blank=True, choices=[('автоматичний', 'Автоматичний'), ('ручний', 'Ручний'), ("п'єзоелектричний", "П'єзоелектричний")], max_length=100, verbose_name='Тип розпалу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_method',
            field=models.CharField(blank=True, choices=[('навісний', 'Навісний'), ('підлоговий', 'Підлоговий'), ('вертикальний', 'Вертикальний'), ('горизонтальний', 'Горизонтальний')], max_length=100, verbose_name='Спосіб установки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pump_type',
            field=models.CharField(blank=True, choices=[('глибинний', 'Глибинний'), ('дренажний', 'Дренажний'), ('поверхневий', 'Поверхневий'), ('занурювальний', 'Занурювальний'), ('каналізаційний', 'Каналізаційний'), ('циркуляційний', 'Циркуляційний')], max_length=100, verbose_name='Тип насосу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_form',
            field=models.CharField(blank=True, choices=[('циліндрична', 'Циліндрична'), ('плоска', 'Плоска')], max_length=100, verbose_name='Форма баку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_type',
            field=models.CharField(blank=True, choices=[('безнапорний', 'Безнапорний'), ('напорний', 'Напорний')], max_length=100, verbose_name='Тип баку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_thrust',
            field=models.CharField(blank=True, choices=[('примусова', 'Примусова'), ('звичайна', 'Звичайна')], max_length=100, verbose_name='Вид тяги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_heater_type',
            field=models.CharField(blank=True, choices=[('накопичувальний', 'Накопичувальний'), ('проточний', 'Проточний')], max_length=100, verbose_name='Тип водонагрівача'),
        ),
        migrations.AlterField(
            model_name='product',
            name='work_type_of_gas_boiler',
            field=models.CharField(blank=True, choices=[('стандартний', 'Стандартний'), ('конденсаційний', 'Конденсаційний')], max_length=100, verbose_name='Принцип роботи газового котла'),
        ),
        migrations.AlterField(
            model_name='product',
            name='work_type_of_solid_fuel_boiler',
            field=models.CharField(blank=True, choices=[('довготривалого горіння', 'Довготривалого горіння'), ('пелетний', 'Пелетний'), ('піролізний', 'Піролізний'), ('стандартний', 'Стандартний')], max_length=100, verbose_name='Принцип роботи твердопаливного котла'),
        ),
    ]
