# Generated by Django 4.0.6 on 2022-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_without_serial_number',
            field=models.CharField(max_length=300, verbose_name='Назва без серійного номеру'),
        ),
    ]
