# Generated by Django 4.0.6 on 2022-09-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_currency_product_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['currency_name']},
        ),
    ]
