# Generated by Django 4.0.6 on 2022-09-13 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_alter_currency_currency_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='boiler_capacity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Місткість водонагрівача (л)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coefficient_of_performance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ККД (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='electric_power',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Електрична потужність (кВт)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heat_area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Максимальна площа обігріву (кв м)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heating_power',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Теплова потужність (кВт)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_fuel_consumption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Максимальна витрата палива (м3/год)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_temperature_water_heating',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Максимальна температура нагріва води (°С)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pressure_in_max',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тиск на вході (max атм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pressure_in_min',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тиск на вході (min атм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productivity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Продуктивність (л/хв)'),
        ),
    ]
