# Generated by Django 4.0.6 on 2022-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Висота (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Глибина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Вага (кг)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
