# Generated by Django 4.0.6 on 2023-01-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_alter_customer_created_at_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='details',
        ),
    ]
